version: '3'

services:
  home-suite-home:
    build: .
    ports:
      - "3000:3000"
  influx:
    image: influxdb:1.3-alpine
    environment:
      - INFLUXDB_DB=homesuitehome
      - INFLUXDB_USER=homesuitehome
      - INFLUXDB_USER_PASSWORD=ReallyLongAndSecurePasswordHere
